In [1]:
print("hi")

hi


In [1]:
from gensim.models import Word2Vec, KeyedVectors
import gensim.downloader as api

print("Gensim imported successfully")

Gensim imported successfully


# This model is trained over the google nbews data, the dimension of this model is 300
# according to the research paper the model is trained in skip gram 

In [2]:
model = api.load("word2vec-google-news-300")

In [4]:
model["computer"]

array([ 1.07421875e-01, -2.01171875e-01,  1.23046875e-01,  2.11914062e-01,
       -9.13085938e-02,  2.16796875e-01, -1.31835938e-01,  8.30078125e-02,
        2.02148438e-01,  4.78515625e-02,  3.66210938e-02, -2.45361328e-02,
        2.39257812e-02, -1.60156250e-01, -2.61230469e-02,  9.71679688e-02,
       -6.34765625e-02,  1.84570312e-01,  1.70898438e-01, -1.63085938e-01,
       -1.09375000e-01,  1.49414062e-01, -4.65393066e-04,  9.61914062e-02,
        1.68945312e-01,  2.60925293e-03,  8.93554688e-02,  6.49414062e-02,
        3.56445312e-02, -6.93359375e-02, -1.46484375e-01, -1.21093750e-01,
       -2.27539062e-01,  2.45361328e-02, -1.24511719e-01, -3.18359375e-01,
       -2.20703125e-01,  1.30859375e-01,  3.66210938e-02, -3.63769531e-02,
       -1.13281250e-01,  1.95312500e-01,  9.76562500e-02,  1.26953125e-01,
        6.59179688e-02,  6.93359375e-02,  1.02539062e-02,  1.75781250e-01,
       -1.68945312e-01,  1.21307373e-03, -2.98828125e-01, -1.15234375e-01,
        5.66406250e-02, -

In [ ]:
model["king"] # vector reprensentation of the word "king"

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [9]:
len(model["king"])

300

In [13]:
model["syntax"] # embedding of the word "syntax"

array([ 2.94921875e-01, -2.08007812e-01, -6.01196289e-03,  2.86865234e-02,
       -1.86523438e-01,  8.93554688e-02,  4.98046875e-02,  9.22851562e-02,
        2.67578125e-01,  1.54296875e-01, -1.82617188e-01, -2.63671875e-01,
       -1.49414062e-01,  1.60156250e-01, -3.11279297e-02,  2.75878906e-02,
        1.37695312e-01,  4.31640625e-01, -2.38281250e-01, -3.47656250e-01,
       -8.74023438e-02,  2.98828125e-01,  1.74804688e-01,  4.73632812e-02,
       -1.72851562e-01, -3.96484375e-01,  4.12597656e-02,  3.58886719e-02,
       -3.63769531e-02,  8.83789062e-02, -1.31835938e-01, -2.16064453e-02,
       -2.05078125e-01, -1.33789062e-01,  6.73828125e-02,  3.39843750e-01,
        2.49023438e-01,  2.83203125e-01,  1.66015625e-01, -1.18652344e-01,
        3.04687500e-01, -2.09960938e-01,  1.49414062e-01,  3.57421875e-01,
        1.72851562e-01,  4.29687500e-02, -3.20312500e-01, -8.34960938e-02,
       -1.87500000e-01, -3.97949219e-02, -1.66992188e-01, -3.33984375e-01,
       -1.70898438e-01, -

In [14]:
 model.most_similar("king") # most similar words to "king"

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [15]:
model["raju"]

array([-4.44335938e-02,  3.91006470e-05,  1.08886719e-01,  6.39648438e-02,
       -6.59179688e-03,  3.85742188e-02,  1.47460938e-01, -6.39648438e-02,
       -1.46484375e-01, -6.37817383e-03,  1.09863281e-02, -1.07910156e-01,
       -1.59179688e-01,  2.10937500e-01, -2.38281250e-01,  2.00195312e-01,
        9.52148438e-02,  7.23266602e-03, -3.80859375e-02, -7.37304688e-02,
       -9.17968750e-02, -1.39648438e-01,  2.89062500e-01, -6.29882812e-02,
       -3.56445312e-02, -1.18652344e-01, -4.73632812e-02,  3.58886719e-02,
       -5.22460938e-02, -7.37304688e-02, -1.14257812e-01,  1.79443359e-02,
        2.67028809e-03,  2.07519531e-02, -9.27734375e-02, -5.34667969e-02,
        2.48718262e-03,  2.23388672e-02,  1.90429688e-01,  6.22558594e-03,
       -1.16577148e-02, -4.83398438e-02,  1.45507812e-01,  6.68945312e-02,
       -7.66601562e-02, -1.70898438e-01, -1.15234375e-01, -9.42382812e-02,
       -6.93359375e-02, -1.05957031e-01, -9.76562500e-02,  6.44531250e-02,
        2.31445312e-01,  

In [18]:
model.most_similar("raju") # most similar words to "raju"

[('kiran', 0.7370322942733765),
 ('ho_sakta', 0.7249269485473633),
 ('krishna', 0.7129136919975281),
 ('kintu', 0.7072979211807251),
 ('kapoor', 0.7071950435638428),
 ('jaisa', 0.7034584283828735),
 ('satyam', 0.7030960917472839),
 ('bilkul', 0.7018522620201111),
 ('sab_hai', 0.701370358467102),
 ('varun', 0.699938178062439)]

In [24]:
model["Andhra"]

array([ 2.03125000e-01,  8.69140625e-02, -1.07910156e-01,  5.39062500e-01,
       -1.00585938e-01, -4.19921875e-01, -9.81445312e-02,  7.47070312e-02,
       -1.73828125e-01,  2.61718750e-01, -8.64257812e-02,  4.79125977e-03,
       -3.88183594e-02, -1.98242188e-01, -1.90429688e-01,  1.31835938e-01,
       -2.79296875e-01, -2.19726562e-01,  2.16796875e-01,  6.07910156e-02,
        2.75390625e-01, -9.71679688e-02, -1.19140625e-01, -3.36914062e-02,
       -9.81445312e-02,  1.38671875e-01, -3.33984375e-01, -1.91406250e-01,
       -1.23046875e-01,  5.85937500e-02, -2.37304688e-01, -7.51953125e-02,
       -1.59179688e-01, -2.22167969e-02, -8.88671875e-02,  1.06811523e-02,
       -2.49023438e-01, -2.69531250e-01,  3.12500000e-01, -8.97216797e-03,
        2.55859375e-01, -4.12597656e-02,  1.56250000e-01,  1.47460938e-01,
        6.88476562e-02, -4.35546875e-01, -1.57226562e-01, -1.64794922e-02,
        3.02734375e-01, -1.28906250e-01, -2.49023438e-01,  9.39941406e-03,
        3.78906250e-01,  

In [25]:
model.most_similar("Andhra") # most similar words to "raju"

[('Andhra_Pradesh', 0.8296653032302856),
 ('Karnataka', 0.8259543776512146),
 ('Tamil_Nadu', 0.7837239503860474),
 ('Maharashtra', 0.7832092642784119),
 ('Tamilnadu', 0.7603269815444946),
 ('Gujarat', 0.741411566734314),
 ('Kerala', 0.7364658713340759),
 ('Saurashtra', 0.7337688207626343),
 ('Madhya_Pradesh', 0.7208116054534912),
 ('Rajasthan', 0.7165015935897827)]

In [26]:
model.similarity("king", "queen") # similarity between "king" and "queen"

np.float32(0.6510957)

In [31]:
model.similarity("Tamil_nadu", "Tamil") # similarity between "raju" and "Andhra"

np.float32(0.48415083)

In [34]:
model.similarity("Telugu", "Andhra_pradesh") # similarity between "king" and "queen"  may be using cosine similarity

np.float32(0.4079323)

In [ ]:
model.similarity("men", "men") 

np.float32(1.0)

In [37]:
model.similarity("king", "robber") # similarity between "king" and "queen"

np.float32(0.11847229)

In [38]:
model.doesnt_match(["breakfast", "lunch", "dinner", "car"]) # which word doesn't match in the list

'car'

In [39]:
vec = model["king"]-model["man"]+model["woman"] #      

In [42]:
model.most_similar([vec]) # most similar words to the vector representation of ") 

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

# average word to vec

In [118]:
sentence = "i love machine learning " # in order to get the sentence to vector we have create a vector for each word in the sentence and then take the average of all the vectors to get the sentence vector

In [119]:
token =sentence.lower().split() # convert the sentence to lower case and then split the sentence into words

In [120]:
word_vec=[]

In [124]:
for word in token:
    print(word)
    word_vec.append(model[word])
    # append the vector representation of each word in the sentence to the list


i
love
machine
learning


In [125]:
len(word_vec)

8

In [123]:
for words , emb in zip(token, word_vec):
    print(words)
    print(emb)

i
[-2.25585938e-01 -1.95312500e-02  9.08203125e-02  2.37304688e-01
 -2.92968750e-02  9.32617188e-02 -5.88378906e-02 -4.10156250e-02
  5.22460938e-02  2.00195312e-02 -3.44238281e-02 -2.91015625e-01
 -2.61718750e-01 -1.90429688e-01  3.85742188e-02  8.30078125e-03
  3.14941406e-02  7.47070312e-02  1.14746094e-01  1.24511719e-02
 -2.11914062e-01  1.28906250e-01  2.55859375e-01  1.08886719e-01
 -7.03125000e-02  1.60156250e-01 -4.00390625e-01 -1.16699219e-01
 -3.22265625e-02 -6.73828125e-02  1.55273438e-01  1.25000000e-01
 -6.22558594e-02  3.56445312e-02 -1.79687500e-01  1.58203125e-01
 -2.53906250e-01  1.74804688e-01 -1.18164062e-01 -2.19726562e-03
  1.49536133e-02 -5.71289062e-02  2.39257812e-01  1.36718750e-01
  1.47460938e-01  7.08007812e-02  1.72851562e-01 -2.38281250e-01
 -5.71289062e-02 -1.04492188e-01  2.23388672e-02  8.74023438e-02
  1.43554688e-01  3.47656250e-01 -9.22851562e-02  2.51953125e-01
 -9.86328125e-02  1.21582031e-01 -1.56250000e-02 -1.08398438e-01
 -2.05078125e-02  1.495

In [63]:
np.mean(word_vec, axis=0) # take the average of all the vectors to get the sentence vector

array([ 1.12304688e-02, -1.13830566e-02,  2.06909180e-02,  1.43615723e-01,
       -3.96728516e-02,  1.39282227e-01,  5.63964844e-02, -2.90527344e-02,
       -1.94091797e-02,  6.54907227e-02,  9.49096680e-03, -1.30126953e-01,
       -1.07116699e-01, -1.29760742e-01,  9.94873047e-03,  7.73925781e-02,
       -4.68139648e-02,  1.51245117e-01,  1.24572754e-01, -1.01013184e-01,
       -7.25708008e-02,  1.22924805e-01,  7.96489716e-02,  1.19506836e-01,
        5.38940430e-02, -4.02832031e-02, -1.22619629e-01, -2.44140625e-04,
        2.44140625e-02, -1.11328125e-01,  1.31835938e-02, -3.17382812e-03,
       -5.45196533e-02,  1.23840332e-01, -6.40258789e-02, -2.56347656e-03,
       -2.30255127e-02,  9.41162109e-02,  3.81469727e-02,  3.29589844e-02,
        1.39480591e-01, -7.67211914e-02,  1.08428955e-01,  3.95202637e-02,
        6.39648438e-02, -6.82373047e-02,  8.05664062e-02,  5.64575195e-02,
       -3.21960449e-02,  4.71801758e-02, -4.17327881e-02,  7.21435547e-02,
       -4.82177734e-03,  

In [62]:
import numpy as np

In [108]:
sen = "i am student in university"

In [126]:
tokens = sen.lower().split()

In [127]:
tokens

['i', 'am', 'student', 'in', 'university']

In [128]:
for word in tokens:
    print(word)

i
am
student
in
university


In [129]:
embeddings = []

In [130]:
for words in tokens:
    embeddings.append(model[words]) # append the vector representation of each word in the sentence to the list

In [131]:
embeddings

[array([-2.25585938e-01, -1.95312500e-02,  9.08203125e-02,  2.37304688e-01,
        -2.92968750e-02,  9.32617188e-02, -5.88378906e-02, -4.10156250e-02,
         5.22460938e-02,  2.00195312e-02, -3.44238281e-02, -2.91015625e-01,
        -2.61718750e-01, -1.90429688e-01,  3.85742188e-02,  8.30078125e-03,
         3.14941406e-02,  7.47070312e-02,  1.14746094e-01,  1.24511719e-02,
        -2.11914062e-01,  1.28906250e-01,  2.55859375e-01,  1.08886719e-01,
        -7.03125000e-02,  1.60156250e-01, -4.00390625e-01, -1.16699219e-01,
        -3.22265625e-02, -6.73828125e-02,  1.55273438e-01,  1.25000000e-01,
        -6.22558594e-02,  3.56445312e-02, -1.79687500e-01,  1.58203125e-01,
        -2.53906250e-01,  1.74804688e-01, -1.18164062e-01, -2.19726562e-03,
         1.49536133e-02, -5.71289062e-02,  2.39257812e-01,  1.36718750e-01,
         1.47460938e-01,  7.08007812e-02,  1.72851562e-01, -2.38281250e-01,
        -5.71289062e-02, -1.04492188e-01,  2.23388672e-02,  8.74023438e-02,
         1.4

In [132]:
len(embeddings[0]) # length of the vector representation of each word in the sentence

300

In [133]:
for words, emb in zip(tokens, embeddings):
    print(words)
    print(emb)

i
[-2.25585938e-01 -1.95312500e-02  9.08203125e-02  2.37304688e-01
 -2.92968750e-02  9.32617188e-02 -5.88378906e-02 -4.10156250e-02
  5.22460938e-02  2.00195312e-02 -3.44238281e-02 -2.91015625e-01
 -2.61718750e-01 -1.90429688e-01  3.85742188e-02  8.30078125e-03
  3.14941406e-02  7.47070312e-02  1.14746094e-01  1.24511719e-02
 -2.11914062e-01  1.28906250e-01  2.55859375e-01  1.08886719e-01
 -7.03125000e-02  1.60156250e-01 -4.00390625e-01 -1.16699219e-01
 -3.22265625e-02 -6.73828125e-02  1.55273438e-01  1.25000000e-01
 -6.22558594e-02  3.56445312e-02 -1.79687500e-01  1.58203125e-01
 -2.53906250e-01  1.74804688e-01 -1.18164062e-01 -2.19726562e-03
  1.49536133e-02 -5.71289062e-02  2.39257812e-01  1.36718750e-01
  1.47460938e-01  7.08007812e-02  1.72851562e-01 -2.38281250e-01
 -5.71289062e-02 -1.04492188e-01  2.23388672e-02  8.74023438e-02
  1.43554688e-01  3.47656250e-01 -9.22851562e-02  2.51953125e-01
 -9.86328125e-02  1.21582031e-01 -1.56250000e-02 -1.08398438e-01
 -2.05078125e-02  1.495

In [135]:
sentence_vector = np.mean(embeddings, axis=0) # take the average of all the vectors to get the sentence vector

In [136]:
sentence_vector

array([-8.75488296e-02, -1.91162117e-02,  1.25732422e-01,  1.36914060e-01,
        9.76097137e-02,  9.27734363e-04,  6.37695342e-02, -6.87133819e-02,
        7.18505830e-02, -6.82617202e-02,  2.13623047e-03, -1.07080080e-01,
       -1.73339844e-02, -6.65039048e-02, -7.06054717e-02,  3.47900391e-03,
       -6.20117188e-02,  7.80273452e-02,  1.17504880e-01, -6.69921860e-02,
       -8.85498077e-02,  9.61914062e-02,  7.15194717e-02, -1.27868652e-02,
       -4.61364761e-02, -8.09570327e-02, -1.60250857e-01, -1.28784182e-03,
        7.64160156e-02,  6.83593750e-03,  1.37011722e-01, -7.54882842e-02,
       -9.60205048e-02, -4.05761711e-02, -9.27734375e-03,  5.84472641e-02,
       -3.56933586e-02,  7.06787109e-02, -6.94335923e-02,  1.20507814e-01,
        1.00219725e-02, -7.32421875e-04,  5.42968735e-02,  5.61889634e-02,
        8.16894546e-02,  2.05078125e-02,  1.78955086e-02, -4.96826172e-02,
       -5.99121079e-02, -1.79595947e-02,  4.46533188e-02, -6.25000009e-03,
        8.40209946e-02,  

In [138]:
sentence_vector.shape

(300,)

# word2vec --> converts words to vector
# average word2vec --> converts every sentence into a vector (averaging the individual words vectors in the sentece)