In [1]:
print("hello venkatesh")

hello venkatesh


In [2]:
print("Hii Venky")

Hii Venky


In [3]:
print("Checking ")

Checking 


# One Hot Encoding 

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [6]:
# Dummy categorical data
categories = np.array([['red'], ['green'], ['blue'], ['green'], ['red'], ['blue']])

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(categories)

print("Original categories:")
print(categories.flatten())
print()
print("One-hot encoded matrix:")
print(encoded)
print()
print("Encoded feature names:")
print(encoder.get_feature_names_out())

Original categories:
['red' 'green' 'blue' 'green' 'red' 'blue']

One-hot encoded matrix:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Encoded feature names:
['x0_blue' 'x0_green' 'x0_red']


In [7]:
documents = [
    "people watch movie",
    "people watch cricket",
    "people like movie",
    "people like cricket"
]

In [8]:
documents 

['people watch movie',
 'people watch cricket',
 'people like movie',
 'people like cricket']

In [9]:
tokens =[sentence.lower().split() for sentence in documents]

In [10]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [11]:
all_words= [[words] for sentence in tokens for words in sentence]

In [ ]:
all_words      # we need to process this data to get the unique words and then we can use one hot encoding to encode the data.

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['like'],
 ['cricket']]

In [22]:
encoder =OneHotEncoder(sparse_output=False)

In [25]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [26]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


In [27]:
encoder.categories_

[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]

In [28]:
# now we need to create the one hot encoder vector for each sentence in the documents list. We can do this by transforming each sentence into a one-hot encoded vector using the fitted encoder.

tokens


[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [48]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nsentence:", sentence)
    print(encoded_sentence)


sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

sentence: ['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [49]:
sentence

['people', 'like', 'cricket']

In [57]:
doc= ["i like pizza", 
      "i like burger"]


In [58]:
tokens= [sentence.lower().split() for sentence in doc]

In [59]:
tokens

[['i', 'like', 'pizza'], ['i', 'like', 'burger']]

In [61]:
all_words= [[words] for sentence in tokens for words in sentence]

In [62]:
all_words

[['i'], ['like'], ['pizza'], ['i'], ['like'], ['burger']]

In [65]:
encoder= OneHotEncoder(sparse_output=False)

In [66]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [72]:
for sentence in tokens:
    endoded_vec = encoder.transform([[words] for words in sentence])
    print("\n sentance:",sentence)
    print(endoded_vec)


 sentance: ['i', 'like', 'pizza']
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 sentance: ['i', 'like', 'burger']
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [76]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['burger' 'i' 'like' 'pizza']


In [115]:
doc=["i am venkatesh",
     " i am from india ", 
     "i am studying in germany"
]

In [116]:
doc

['i am venkatesh', ' i am from india ', 'i am studying in germany']

In [117]:
tokens = [sentence.lower().split() for sentence in doc]

In [118]:
tokens

[['i', 'am', 'venkatesh'],
 ['i', 'am', 'from', 'india'],
 ['i', 'am', 'studying', 'in', 'germany']]

In [119]:
all_words=[[words] for sentence in tokens for words in sentence]

In [120]:
all_words

[['i'],
 ['am'],
 ['venkatesh'],
 ['i'],
 ['am'],
 ['from'],
 ['india'],
 ['i'],
 ['am'],
 ['studying'],
 ['in'],
 ['germany']]

In [121]:
encoder=OneHotEncoder(sparse_output=False)

In [122]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [125]:
for sentence in tokens:
    encoder_vector=encoder.transform([[words] for words in sentence])
    print("\n sentence:",sentence)
    print(encoder_vector)


 sentence: ['i', 'am', 'venkatesh']
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

 sentence: ['i', 'am', 'from', 'india']
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]

 sentence: ['i', 'am', 'studying', 'in', 'germany']
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


In [124]:
encoder.categories_

[array(['am', 'from', 'germany', 'i', 'in', 'india', 'studying',
        'venkatesh'], dtype=object)]