In [1]:
print("hello venkatesh")

hello venkatesh


In [2]:
print("Hii Venky")

Hii Venky


In [3]:
print("Checking ")

Checking 


# One Hot Encoding 

In [5]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [6]:
# Dummy categorical data
categories = np.array([['red'], ['green'], ['blue'], ['green'], ['red'], ['blue']])

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(categories)

print("Original categories:")
print(categories.flatten())
print()
print("One-hot encoded matrix:")
print(encoded)
print()
print("Encoded feature names:")
print(encoder.get_feature_names_out())

Original categories:
['red' 'green' 'blue' 'green' 'red' 'blue']

One-hot encoded matrix:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Encoded feature names:
['x0_blue' 'x0_green' 'x0_red']


In [7]:
documents = [
    "people watch movie",
    "people watch cricket",
    "people like movie",
    "people like cricket"
]

In [8]:
documents 

['people watch movie',
 'people watch cricket',
 'people like movie',
 'people like cricket']

In [9]:
tokens =[sentence.lower().split() for sentence in documents]

In [10]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [11]:
all_words= [[words] for sentence in tokens for words in sentence]

In [ ]:
all_words      # we need to process this data to get the unique words and then we can use one hot encoding to encode the data.

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['like'],
 ['cricket']]

In [22]:
encoder =OneHotEncoder(sparse_output=False)

In [25]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [26]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


In [27]:
encoder.categories_

[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]

In [28]:
# now we need to create the one hot encoder vector for each sentence in the documents list. We can do this by transforming each sentence into a one-hot encoded vector using the fitted encoder.

tokens


[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [48]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nsentence:", sentence)
    print(encoded_sentence)


sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

sentence: ['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [49]:
sentence

['people', 'like', 'cricket']

In [57]:
doc= ["i like pizza", 
      "i like burger"]


In [58]:
tokens= [sentence.lower().split() for sentence in doc]

In [59]:
tokens

[['i', 'like', 'pizza'], ['i', 'like', 'burger']]

In [61]:
all_words= [[words] for sentence in tokens for words in sentence]

In [62]:
all_words

[['i'], ['like'], ['pizza'], ['i'], ['like'], ['burger']]

In [65]:
encoder= OneHotEncoder(sparse_output=False)

In [66]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [72]:
for sentence in tokens:
    endoded_vec = encoder.transform([[words] for words in sentence])
    print("\n sentance:",sentence)
    print(endoded_vec)


 sentance: ['i', 'like', 'pizza']
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 sentance: ['i', 'like', 'burger']
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [76]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['burger' 'i' 'like' 'pizza']


In [167]:
doc=["i am venkatesh",
     " i am from india ", 
     "i am studying in germany"
]

In [300]:
doc=["i am venkatesh",
     " i am from india ", 
     "i am studying in germany"
]

In [301]:
tokens = [sentence.lower().split() for sentence in doc]

In [302]:
tokens

[['i', 'am', 'venkatesh'],
 ['i', 'am', 'from', 'india'],
 ['i', 'am', 'studying', 'in', 'germany']]

In [303]:
all_words= [[words] for sentence in tokens for words in sentence]

In [304]:
all_words

[['i'],
 ['am'],
 ['venkatesh'],
 ['i'],
 ['am'],
 ['from'],
 ['india'],
 ['i'],
 ['am'],
 ['studying'],
 ['in'],
 ['germany']]

In [307]:
encoder=OneHotEncoder(sparse_output=False) 

In [308]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [312]:
for sentence in tokens:
    encoded_vector=encoder.transform([[words] for words in sentence])
    print("sentence:",sentence)
    print("vocabulary:",encoder.categories_[0])
    print("encoded vector:",encoded_vector)

sentence: ['i', 'am', 'venkatesh']
vocabulary: ['am' 'from' 'germany' 'i' 'in' 'india' 'studying' 'venkatesh']
encoded vector: [[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
sentence: ['i', 'am', 'from', 'india']
vocabulary: ['am' 'from' 'germany' 'i' 'in' 'india' 'studying' 'venkatesh']
encoded vector: [[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]
sentence: ['i', 'am', 'studying', 'in', 'germany']
vocabulary: ['am' 'from' 'germany' 'i' 'in' 'india' 'studying' 'venkatesh']
encoded vector: [[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


In [168]:
doc

['i am venkatesh', ' i am from india ', 'i am studying in germany']

In [169]:
tokens = [sentence.lower().split() for sentence in doc]

In [170]:
tokens

[['i', 'am', 'venkatesh'],
 ['i', 'am', 'from', 'india'],
 ['i', 'am', 'studying', 'in', 'germany']]

In [171]:
all_words=[[words] for sentence in tokens for words in sentence]

In [172]:
all_words

[['i'],
 ['am'],
 ['venkatesh'],
 ['i'],
 ['am'],
 ['from'],
 ['india'],
 ['i'],
 ['am'],
 ['studying'],
 ['in'],
 ['germany']]

In [173]:
encoder=OneHotEncoder(sparse_output=False) #sparse_output=False means that the output will be a dense array instead of a sparse matrix.

In [174]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [175]:
for sentence in tokens:
    encoder_vector=encoder.transform([[words] for words in sentence])
    print("\n sentence:",sentence)
    print(encoder_vector)


 sentence: ['i', 'am', 'venkatesh']
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

 sentence: ['i', 'am', 'from', 'india']
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]]

 sentence: ['i', 'am', 'studying', 'in', 'germany']
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


In [176]:
encoder.categories_

[array(['am', 'from', 'germany', 'i', 'in', 'india', 'studying',
        'venkatesh'], dtype=object)]

In [177]:
tokens

[['i', 'am', 'venkatesh'],
 ['i', 'am', 'from', 'india'],
 ['i', 'am', 'studying', 'in', 'germany']]

In [233]:
document=["i am venkatesh i love AI"]

In [234]:
tokens=[sentence.lower().split() for sentence in document]


In [235]:
tokens

[['i', 'am', 'venkatesh', 'i', 'love', 'ai']]

In [236]:
all_word=[[words] for sentence in tokens for words in sentence]

In [237]:
all_word

[['i'], ['am'], ['venkatesh'], ['i'], ['love'], ['ai']]

In [246]:
encoder=OneHotEncoder(sparse_output=False)

In [247]:
encoder.fit(all_word)  # here it can learn the unique words in the all_word list and then it can create a one hot encoder vector for each word in the all_word list.

OneHotEncoder(sparse_output=False)

In [248]:
for  sentence in tokens:
    encoder_vector =encoder.fit_transform(all_word)
    print("\n sentence:",sentence)
    print(encoder.categories_[0])
    print("Encoder Vector:", encoder_vector)
    
    


 sentence: ['i', 'am', 'venkatesh', 'i', 'love', 'ai']
['ai' 'am' 'i' 'love' 'venkatesh']
Encoder Vector: [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]


# Bag of words

In [200]:
from sklearn.feature_extraction.text import CountVectorizer

In [225]:

documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [226]:
bow_vector = CountVectorizer()

In [227]:
bow_matrix = bow_vector.fit_transform(documents)

In [228]:
bow_matrix.toarray()  # this will give us the bag of words representation of the documents. Each row represents a document and each column represents a unique word in the vocabulary. The value in each cell represents the count of the word in the document.

array([[1, 1, 0, 0, 0, 2, 1, 2],
       [0, 1, 2, 0, 0, 0, 1, 2],
       [0, 1, 0, 2, 1, 2, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [232]:
print(bow_vector.get_feature_names_out())
print("bow matrix \n", bow_matrix.toarray())


['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
bow matrix 
 [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]


In [231]:
print(bow_vector.get_feature_names_out())

['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


In [291]:
documents = ["hi i am venkatesh and i love AI and i am doing my masters in germany"]

In [292]:
bow=CountVectorizer()

In [293]:
bow_matrix = bow.fit_transform(documents)

In [294]:
print(bow.get_feature_names_out())
print("Bow Matrix:\n", bow_matrix.toarray())

['ai' 'am' 'and' 'doing' 'germany' 'hi' 'in' 'love' 'masters' 'my'
 'venkatesh']
Bow Matrix:
 [[1 2 2 1 1 1 1 1 1 1 1]]


In [296]:
documents = ["lion is the king of the jungle and tiger is the king of the forest"]

In [297]:
bow.fit(documents)

CountVectorizer()

In [298]:
print("sentence",documents)
bow.transform(documents).toarray()  # this will give us the bag of words representation of the documents. Each row represents a document and each column represents a unique word in the vocabulary. The value in each cell represents the count of the word in the document.

sentence ['lion is the king of the jungle and tiger is the king of the forest']


array([[1, 1, 2, 1, 2, 1, 2, 4, 1]], dtype=int64)

In [299]:
print("Vocabulary:", bow.get_feature_names_out())

Vocabulary: ['and' 'forest' 'is' 'jungle' 'king' 'lion' 'of' 'the' 'tiger']


In [313]:
document =["venkatesh is the good boy and he is doing his masters in germany and he is learning AI"]

In [326]:
bow1=CountVectorizer()

In [316]:
from sklearn.feature_extraction.text import CountVectorizer

In [327]:
vector =bow1.fit_transform(document)

In [322]:
vector

<1x14 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [331]:
print(bow1.get_feature_names_out())
print(document)
vector.toarray()  # this will give us the bag of words representation of the documents. Each row represents a document and each column represents a unique word in the vocabulary. The value in each cell represents the count of the word in the document.

['ai' 'and' 'boy' 'doing' 'germany' 'good' 'he' 'his' 'in' 'is' 'learning'
 'masters' 'the' 'venkatesh']
['venkatesh is the good boy and he is doing his masters in germany and he is learning AI']


array([[1, 2, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1]], dtype=int64)

In [329]:
bow1.get_feature_names_out()

array(['ai', 'and', 'boy', 'doing', 'germany', 'good', 'he', 'his', 'in',
       'is', 'learning', 'masters', 'the', 'venkatesh'], dtype=object)